version: '3'

services:
   db:
     image: mysql:5.7
     platform: linux/amd64  # Intelチップの場合不要
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     build: .
     depends_on:
       - db
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     hostname: wordpress
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./wordpress:/var/www/html
       - ./php/php.ini:/usr/local/etc/php/php.ini
       - ./init_wp.sh:/var/www/html/init_wp.sh
       - ./plugin_install.sh:/var/www/html/plugin_install.sh
       - ./plugin_uninstall.sh:/var/www/html/plugin_uninstall.sh
volumes:
  db_data:
