# Plugin インストール 
wp plugin install add-to-any --allow-root
wp plugin install admin-menu-editor --allow-root
wp plugin install adminimize --allow-root
wp plugin install advanced-custom-fields --allow-root
wp plugin install akismet --allow-root
wp plugin install all-in-one-seo-pack --allow-root
wp plugin install all-in-one-wp-migration --allow-root
wp plugin install aryo-activity-log --allow-root
wp plugin install backwpup --allow-root
wp plugin install breadcrumb-navxt --allow-root
wp plugin install classic-editor --allow-root
wp plugin install classic-widgets --allow-root
wp plugin install codepress-admin-columns --allow-root
wp plugin install comment-reply-email-notification --allow-root
wp plugin install contact-form-7 --allow-root
wp plugin install cookie-law-info --allow-root
wp plugin install custom-field-suite --allow-root
wp plugin install custom-field-template --allow-root
wp plugin install custom-permalinks --allow-root
wp plugin install custom-post-type-permalinks --allow-root
wp plugin install custom-post-type-ui --allow-root
wp plugin install custom-post-types-relationships-cptr --allow-root
wp plugin install custom-upload-dir --allow-root
wp plugin install disable-wp-rest-api --allow-root
#wp plugin install dorzki-notifications-to-slack --allow-root
wp plugin install download-monitor --allow-root
wp plugin install duplicate-page --allow-root
wp plugin install duplicate-post --allow-root
wp plugin install email-log --allow-root
wp plugin install enable-media-replace --allow-root
wp plugin install ewww-image-optimizer --allow-root
wp plugin install exclude-pages --allow-root
wp plugin install fv-top-level-cats --allow-root
wp plugin install get-filesize-shortcode --allow-root
wp plugin install google-sitemap-generator --allow-root
wp plugin install gtranslate --allow-root
wp plugin install hello-dolly --allow-root
wp plugin install http-auth --allow-root
wp plugin install index.php --allow-root
wp plugin install infinite-scroll --allow-root
wp plugin install instagrate-to-wordpress --allow-root
wp plugin install intuitive-custom-post-order --allow-root
wp plugin install logbook --allow-root
wp plugin install loginizer --allow-root
wp plugin install mw-wp-form --allow-root
wp plugin install no-category-base-wpml --allow-root
wp plugin install no-login-by-email-address --allow-root
wp plugin install pdf-embedder --allow-root
wp plugin install post-snippets --allow-root
wp plugin install public-post-preview --allow-root
wp plugin install public-post-preview-configurator --allow-root
wp plugin install redirection --allow-root
wp plugin install regenerate-thumbnails --allow-root
wp plugin install rest-xmlrpc-data-checker --allow-root
wp plugin install revision-manager-tmc --allow-root
wp plugin install search-filter --allow-root
wp plugin install search-regex --allow-root
wp plugin install seo-simple-pack --allow-root
wp plugin install show-current-template --allow-root
wp plugin install simple-301-redirects --allow-root
wp plugin install simple-tags --allow-root
wp plugin install siteguard --allow-root
wp plugin install tag-groups --allow-root
wp plugin install taxonomy-terms-order --allow-root
wp plugin install the-events-calendar --allow-root
wp plugin install the-events-calendar-shortcode --allow-root
wp plugin install tiny-compress-images --allow-root
wp plugin install tinymce-advanced --allow-root
wp plugin install user-role-editor --allow-root
wp plugin install wc-shortcodes --allow-root
wp plugin install wordpress-importer --allow-root
wp plugin install wordpress-popular-posts --allow-root
wp plugin install wp-force-login --allow-root
wp plugin install wp-mail-smtp --allow-root
wp plugin install wp-maintenance-mode --allow-root
wp plugin install wp-multibyte-patch --allow-root
wp plugin install wp-pagenavi --allow-root
wp plugin install wp-postratings --allow-root
wp plugin install wp-saml-auth --allow-root
wp plugin install wp-super-cache --allow-root
wp plugin install wp-user-avatar --allow-root
wp plugin install yet-another-related-posts-plugin --allow-root
