# Plugin インストール 
wp plugin uninstall add-to-any  --allow-root
wp plugin uninstall admin-menu-editor  --allow-root
wp plugin uninstall adminimize  --allow-root
wp plugin uninstall advanced-custom-fields  --allow-root
wp plugin uninstall akismet  --allow-root
wp plugin uninstall all-in-one-seo-pack  --allow-root
wp plugin uninstall all-in-one-wp-migration  --allow-root
wp plugin uninstall aryo-activity-log  --allow-root
wp plugin uninstall backwpup  --allow-root
wp plugin uninstall breadcrumb-navxt  --allow-root
wp plugin uninstall classic-editor  --allow-root
wp plugin uninstall classic-widgets  --allow-root
wp plugin uninstall codepress-admin-columns  --allow-root
wp plugin uninstall comment-reply-email-notification  --allow-root
wp plugin uninstall contact-form-7  --allow-root
wp plugin uninstall cookie-law-info  --allow-root
wp plugin uninstall custom-field-suite  --allow-root
wp plugin uninstall custom-field-template  --allow-root
wp plugin uninstall custom-permalinks  --allow-root
wp plugin uninstall custom-post-type-permalinks  --allow-root
wp plugin uninstall custom-post-type-ui  --allow-root
wp plugin uninstall custom-post-types-relationships-cptr  --allow-root
wp plugin uninstall custom-upload-dir  --allow-root
wp plugin uninstall disable-wp-rest-api  --allow-root
wp plugin uninstall download-monitor  --allow-root
wp plugin uninstall duplicate-page  --allow-root
wp plugin uninstall duplicate-post  --allow-root
wp plugin uninstall email-log  --allow-root
wp plugin uninstall enable-media-replace  --allow-root
wp plugin uninstall ewww-image-optimizer  --allow-root
wp plugin uninstall exclude-pages  --allow-root
wp plugin uninstall fv-top-level-cats  --allow-root
wp plugin uninstall get-filesize-shortcode  --allow-root
wp plugin uninstall google-sitemap-generator  --allow-root
wp plugin uninstall gtranslate  --allow-root
wp plugin uninstall hello-dolly  --allow-root
wp plugin uninstall http-auth  --allow-root
wp plugin uninstall infinite-scroll  --allow-root
wp plugin uninstall instagrate-to-wordpress  --allow-root
wp plugin uninstall intuitive-custom-post-order  --allow-root
wp plugin uninstall logbook  --allow-root
wp plugin uninstall loginizer  --allow-root
wp plugin uninstall mw-wp-form  --allow-root
wp plugin uninstall no-category-base-wpml  --allow-root
wp plugin uninstall no-login-by-email-address  --allow-root
wp plugin uninstall pdf-embedder  --allow-root
wp plugin uninstall post-snippets  --allow-root
wp plugin uninstall public-post-preview  --allow-root
wp plugin uninstall public-post-preview-configurator  --allow-root
wp plugin uninstall redirection  --allow-root
wp plugin uninstall regenerate-thumbnails  --allow-root
wp plugin uninstall rest-xmlrpc-data-checker  --allow-root
wp plugin uninstall revision-manager-tmc  --allow-root
wp plugin uninstall search-filter  --allow-root
wp plugin uninstall search-regex  --allow-root
wp plugin uninstall seo-simple-pack  --allow-root
wp plugin uninstall show-current-template  --allow-root
wp plugin uninstall simple-301-redirects  --allow-root
wp plugin uninstall simple-tags  --allow-root
wp plugin uninstall siteguard  --allow-root
wp plugin uninstall tag-groups  --allow-root
wp plugin uninstall taxonomy-terms-order  --allow-root
wp plugin uninstall the-events-calendar  --allow-root
wp plugin uninstall the-events-calendar-shortcode  --allow-root
wp plugin uninstall tiny-compress-images  --allow-root
wp plugin uninstall tinymce-advanced  --allow-root
wp plugin uninstall user-role-editor  --allow-root
wp plugin uninstall wc-shortcodes  --allow-root
wp plugin uninstall wordpress-importer  --allow-root
wp plugin uninstall wordpress-popular-posts  --allow-root
wp plugin uninstall wp-force-login  --allow-root
wp plugin uninstall wp-mail-smtp  --allow-root
wp plugin uninstall wp-maintenance-mode  --allow-root
wp plugin uninstall wp-multibyte-patch  --allow-root
wp plugin uninstall wp-pagenavi  --allow-root
wp plugin uninstall wp-postratings  --allow-root
wp plugin uninstall wp-saml-auth  --allow-root
wp plugin uninstall wp-super-cache  --allow-root
wp plugin uninstall wp-user-avatar  --allow-root
wp plugin uninstall yet-another-related-posts-plugin  --allow-root
